### ISSUE TITLE
2020-04-20 tc1513 M2SD VSSOW parameter scale/unit is incorrect and missing from warning in STDOUT

### ISSUE THREAD

**Issue by TomTensfeldt** [tensfeldt/openNCA#216] opened 2020-04-04 17:40 UTC
Unit Conversion not applied for VSSOW Parameter: Should have units of L/kg, but the scale of values is consistent with units of mL/kg (1000x larger).  

VSSOW is not included in the comment describing unit conversions: 
## unit_conversion : Unit Class 4 (Volume) volume_col:  V0 VZO VZP VSSO VSSP VSSPW  parameters are scaled from  ML  to  L  via scaling factor:  0.001  

Refer to 2020-04-03_tc1513_M2SD.html

**Comment by jhhughes256** [comment] 2020-05-08 14:05
I can replicate this issue, while the automated testcase tc1513_M2SD_ed0aed3.html no longer shows this behaviour.

This is due to the mct having no value for NORMBSU. This causes the volume to be 1000x greater and for `r$VOLUMEWU` to be `NA`.

As of commit ed0aed3, with the following mct I am not able to replicate this.

```r
> paste(testcase.id, mct$MODEL, mct$DOSINGTYPE, mct$AUCMETHOD, mct$TIME, sep = ".")
[1] "tc1513.M2.SD.LINLOG.NOMINAL"
> mct[grep("OUTPUTUNIT$", names(mct))]
  TIMEOUTPUTUNIT AMOUNTOUTPUTUNIT DOSEOUTPUTUNIT VOLUMEOUTPUTUNIT CONCOUTPUTUNIT
1             HR               NA             MG                L          NG/ML
  KELOUTPUTUNIT CLOUTPUTUNIT AUCOUTPUTUNIT AUMCOUTPUTUNIT AUCNORMOUTPUTUNIT
1          1/HR        ML/HR      NG.HR/ML    NG.HR.HR/ML       NG.HR/ML/MG
  AUROUTPUTUNIT CONCNORMOUTPUTUNIT RATEOUTPUTUNIT VOLUMENORMOUTPUTUNIT
1            NA           NG/ML/MG             NA                 L/KG
  CLNORMOUTPUTUNIT
1         ML/HR/KG
> mct[grep("^NORMBS", names(mct))]
  NORMBS NORMBSU
1  WTRAW   WTUNI
```

I'm not certain what the intended behaviour is when you don't provide a unit for the NORMBS column, so I don't know if this issue is closed or not.

**Comment by TomTensfeldt** [comment] 2020-05-08 14:10
For now consider missing NORMBS a configuration error if normalized parameters are selected in the PARAMETERLIST. The computation engine should report the conflict, decline to compute the requested body size normalized parameters but not crash/fail.

**Comment by jhhughes256** [comment] 2020-05-08 14:15
If that's the case then `r$VSSOW`, `r$CLOW` (and other weight-normalised clearance and volumes) should be `NA` if no value is given for `NORMBSU` in the `mct`. 

This is the underlying problem for this issue (with VSSOW reported as x1000 fold higher being a side-effect), so I will leave it open.

**Comment by jhhughes256** [comment] 2020-05-14 18:11
This is not an issue with VSSOW, but instead an issue with the handling of mct$NORMBSU when it is not a valid. Closing this and related issues.

**Closed by jhhughes256** 2020-05-14 18:11 UTC

**Comment by jhhughes256** [comment] 2020-05-14 19:35
linking #247
